name: lint

on:
  schedule:
    - cron: "30 01 * * *"
  push:
    branches: ['*'] 
  pull_request:
    types: [opened, synchronize]

jobs:
  mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v4

      - name: Install packages
        run: bun install

      - name: Build packages
        run: bunx expo-doctor
