name: prebuild

on:
  schedule:
    - cron: "30 01 * * *"
  push:
    branches: ['*']
  pull_request:
    types: [opened, synchronize]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
    - name: Setup repository
      uses: actions/checkout@v4

    - name: prebuild android
      uses: npx expo prebuild -p android --clean
